---
- name: Prueba con WHEN. Actualizar PHP si es menor de 8.1
  hosts: ubuntu1

  tasks:

  - name: Comprobar versión de PHP
    ansible.builtin.shell:
      cmd: php -v | php --version | head -n 1 | cut -c 5-10
    register: resultado
    
  - name: Visualizar resultado. Solo como ejemplo
    ansible.builtin.debug:
      msg: "{{resultado.stdout}}"
    when: resultado.stdout != "8.1.17"
    
  - name: Actualizar PHP
    ansible.builtin.apt:
      name: php8.1
    when: resultado.stdout != "8.1.17"