--
- name: Otras pruebas con LOOP
  hosts: debian1

  tasks:
  - name: Ver las máquinas del inventario
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop: "{{ groups['all'] }}" 
    register: resultado

  - name: Copiar el resultado en mi debian1
    ansible.builtin.copy:
      content: "{{resultado}}"
      dest: /tmp/resultado.txt

  - name: recuperar fichero
    ansible.builtin.fetch:
      src: /tmp/resultado.txt
      dest: /tmp/resultado.txt
      flat: true
      
  
      
    

