---
- name: Bucle con indice
  hosts: debian1

  tasks:
  - name: Índices
    ansible.builtin.debug:
      msg: "{{item}} esta en la posicion {{indice}}"    
    loop:  
       - pepe
       - juan
       - antonio
    loop_control: 
      index_var: indice
    when: indice == 1