---
- name: Prueba con WHEN. Instalar PHP antiguo
  hosts: ubuntu1

  tasks:

  - name: instalar gpg
    ansible.builtin.apt:
      name: gpg
        
  - name: Actualizar repositorio de php
    ansible.builtin.shell:
      cmd: add-apt-repository ppa:ondrej/php  -y

  - name: Actualizar cache apt
    ansible.builtin.apt:
      update_cache: true
      force_apt_get: true
  
  - name: Instalar version antigua de PHP
    ansible.builtin.apt:
      name: php7.4
