---
- name: Crear usuarios con bucles
  hosts: debian1
  vars_files: list_usu.yaml
  tasks:
  - name: Crear varios usuarios en el Sistema Operativo con un fichero externo
    
    ansible.builtin.user:
     name: "{{item}}"
     state: present
    loop: "{{usuarios}}"