
---
- name: Prueba con WHEN. Uso con Variables
  hosts: debian1
  vars:
      ejecutar: True

  tasks:
  - name: Instalar GIT
    ansible.builtin.apt:
     name: git
     state: present
    when:  not ejecutar
    
